[package]
name = "sealevel-program"
version = "0.0.0"
description = "A library for building Sealevel programs"
authors = ["Sealevel Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/sealevel"
homepage = "https://solana.com/"
license = "Apache-2.0"
edition = "2018"
