[package]
name = "sealevel-runtime"
version = "0.0.0"
description = "The runtime for Sealevel programs"
authors = ["Sealevel Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/sealevel"
homepage = "https://solana.com/"
license = "Apache-2.0"
edition = "2018"
